# Generated by Django 4.1.1 on 2022-09-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('price', models.CharField(max_length=180)),
                ('created_by', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=180)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
