# Generated by Django 4.1.1 on 2022-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_alldata_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
